
# **Assignment 1**



## **1. Frailty Analysis**

In [7]:
import pandas as pd
import numpy as np


* pandas libarary is used for the data manipulation and analysis.
* numpy libarary is used for the mathematical operations.

### **Stage 1: Ingest (Data input)**

In [8]:
df = pd.read_csv("../data_raw/Frailty Analysis data.csv")
print("Raw Data:")
display(df)

Raw Data:

   Height_in  Weight_lb  Age  Grip_strength Frailty
0       65.8        112   30             30       N
1       71.5        136   19             31       N
2       69.4        153   45             29       N
3       68.2        142   22             28       Y
4       67.8        144   29             24       Y
5       68.7        123   50             26       N
6       69.8        141   51             22       Y
7       70.1        136   23             20       Y
8       67.9        112   17             19       N
9       66.8        120   39             31       N

In [9]:
# Save to csv
df.to_csv("../data_clean/Frailty Analysis data.csv", index=False)

# reading back the saved csv from cleaned folder
df = pd.read_csv("../data_clean/Frailty Analysis data.csv")
df.head()

   Height_in  Weight_lb  Age  Grip_strength Frailty
0       65.8        112   30             30       N
1       71.5        136   19             31       N
2       69.4        153   45             29       N
3       68.2        142   22             28       Y
4       67.8        144   29             24       Y

### **Stage 2: Process (Data Processing)**

**(a) Unit Standardization:**


First, height is converted from inches to meters using the formula: inches * 0.0254.


Next, weight is converted from lb to kilograms using the formula: lb * 0.45359237

In [10]:
df["Height_m"] = df["Height_in"] * 0.0254
df["Weight_kg"] = df["Weight_lb"] * 0.45359237
display(df)

   Height_in  Weight_lb  Age  Grip_strength Frailty  Height_m  Weight_kg
0       65.8        112   30             30       N   1.67132  50.802345
1       71.5        136   19             31       N   1.81610  61.688562
2       69.4        153   45             29       N   1.76276  69.399633
3       68.2        142   22             28       Y   1.73228  64.410117
4       67.8        144   29             24       Y   1.72212  65.317301
5       68.7        123   50             26       N   1.74498  55.791862
6       69.8        141   51             22       Y   1.77292  63.956524
7       70.1        136   23             20       Y   1.78054  61.688562
8       67.9        112   17             19       N   1.72466  50.802345
9       66.8        120   39             31       N   1.69672  54.431084

**(b) Feature Engineering:**


BMI is calculated using the formula: weight (kg) / height (m)².


The age groups are separated into four categories: <30, 30–45, 46–60, and >60.

In [11]:
df["BMI"] = (df["Weight_kg"] / (df["Height_m"]**2)).round(2)
display (df)

,Height_in,Weight_lb,Age,Grip_strength,Frailty,Height_m,Weight_kg,BMI
0,65.8,112,30,30,N,1.67132,50.802345,18.19
1,71.5,136,19,31,N,1.81610,61.688562,18.70
2,69.4,153,45,29,N,1.76276,69.399633,22.33
3,68.2,142,22,28,Y,1.73228,64.410117,21.46
4,67.8,144,29,24,Y,1.72212,65.317301,22.02
5,68.7,123,50,26,N,1.74498,55.791862,18.32
6,69.8,141,51,22,Y,1.77292,63.956524,20.35
7,70.1,136,23,20,Y,1.78054,61.688562,19.46
8,67.9,112,17,19,N,1.72466,50.802345,17.08
9,66.8,120,39,31,N,1.69672,54.431084,18.91

In [12]:
def age_group(age):
    if age < 30:
        return "<30"
    elif 30 <= age <= 45:
        return "30-45"
    elif 46 <= age <= 60:
        return "46-60"
    else:
        return ">60"

df["AgeGroup"] = df["Age"].apply(age_group)
display(df)

,Height_in,Weight_lb,Age,Grip_strength,Frailty,Height_m,Weight_kg,BMI,AgeGroup
0,65.8,112,30,30,N,1.67132,50.802345,18.19,30-45
1,71.5,136,19,31,N,1.81610,61.688562,18.70,<30
2,69.4,153,45,29,N,1.76276,69.399633,22.33,30-45
3,68.2,142,22,28,Y,1.73228,64.410117,21.46,<30
4,67.8,144,29,24,Y,1.72212,65.317301,22.02,<30
5,68.7,123,50,26,N,1.74498,55.791862,18.32,46-60
6,69.8,141,51,22,Y,1.77292,63.956524,20.35,46-60
7,70.1,136,23,20,Y,1.78054,61.688562,19.46,<30
8,67.9,112,17,19,N,1.72466,50.802345,17.08,<30
9,66.8,120,39,31,N,1.69672,54.431084,18.91,30-45

**(c) Categorical → Numeric Encoding:**

By using the map function, 'N' is converted to 0 and 'Y' is converted to 1

int8 makes the column memory-efficient

In [14]:
df["Frailty_binary"] = df["Frailty"].str.strip().map({"N":0, "Y":1}).astype("int8")
display(df)

,Height_in,Weight_lb,Age,Grip_strength,Frailty,Height_m,Weight_kg,BMI,AgeGroup,Frailty_binary
0,65.8,112,30,30,N,1.67132,50.802345,18.19,30-45,0
1,71.5,136,19,31,N,1.81610,61.688562,18.70,<30,0
2,69.4,153,45,29,N,1.76276,69.399633,22.33,30-45,0
3,68.2,142,22,28,Y,1.73228,64.410117,21.46,<30,1
4,67.8,144,29,24,Y,1.72212,65.317301,22.02,<30,1
5,68.7,123,50,26,N,1.74498,55.791862,18.32,46-60,0
6,69.8,141,51,22,Y,1.77292,63.956524,20.35,46-60,1
7,70.1,136,23,20,Y,1.78054,61.688562,19.46,<30,1
8,67.9,112,17,19,N,1.72466,50.802345,17.08,<30,0
9,66.8,120,39,31,N,1.69672,54.431084,18.91,30-45,0

**One-hot encoding AgeGroup**

Converts the AgeGroup column into separate dummy variables:

AgeGroup_<30, AgeGroup_30-45, AgeGroup_46-60, AgeGroup_>60 and If a person belongs to a particular age group, the value is 1; otherwise, it is 0.

In [15]:
df["AgeGroup <30"] = np.where(df["AgeGroup"] == '<30', 1, 0)
df["AgeGroup 30_45"] = np.where(df["AgeGroup"] == '30-45', 1, 0)
df["AgeGroup 40_60"] = np.where(df["AgeGroup"] == '45-60', 1, 0)
df["AgeGroup >60"] = np.where(df["AgeGroup"] == '>60', 1, 0)
display(df)

,Height_in,Weight_lb,Age,Grip_strength,Frailty,Height_m,Weight_kg,BMI,AgeGroup,Frailty_binary,AgeGroup <30,AgeGroup 30_45,AgeGroup 40_60,AgeGroup >60
0,65.8,112,30,30,N,1.67132,50.802345,18.19,30-45,0,0,1,0,0
1,71.5,136,19,31,N,1.81610,61.688562,18.70,<30,0,1,0,0,0
2,69.4,153,45,29,N,1.76276,69.399633,22.33,30-45,0,0,1,0,0
3,68.2,142,22,28,Y,1.73228,64.410117,21.46,<30,1,1,0,0,0
4,67.8,144,29,24,Y,1.72212,65.317301,22.02,<30,1,1,0,0,0
5,68.7,123,50,26,N,1.74498,55.791862,18.32,46-60,0,0,0,0,0
6,69.8,141,51,22,Y,1.77292,63.956524,20.35,46-60,1,0,0,0,0
7,70.1,136,23,20,Y,1.78054,61.688562,19.46,<30,1,1,0,0,0
8,67.9,112,17,19,N,1.72466,50.802345,17.08,<30,0,1,0,0,0
9,66.8,120,39,31,N,1.69672,54.431084,18.91,30-45,0,0,1,0,0

### **Stage 3: Analyze (Data Analysis)**

**(d) EDA & Reporting**

i) Summary statistics:

*  df.describe() generates statistics for each numeric column.
*  ".T" transposes rows/columns for better readability.
*  We select mean, std, min, and max values.
* This helps understand the distribution of data

In [16]:
summary_stats = df.describe().T[["mean","std","min","max"]]
display(summary_stats)

                      mean        std         min         max
Height_in        68.600000   1.670662   65.800000   71.500000
Weight_lb       131.900000  14.231811  112.000000  153.000000
Age              32.500000  12.860361   17.000000   51.000000
Grip_strength    26.000000   4.521553   19.000000   31.000000
Height_m          1.742440   0.042435    1.671320    1.816100
Weight_kg        59.828834   6.455441   50.802345   69.399633
BMI              19.682000   1.780972   17.080000   22.330000
Frailty_binary    0.400000   0.516398    0.000000    1.000000
AgeGroup <30      0.500000   0.527046    0.000000    1.000000
AgeGroup 30_45    0.300000   0.483046    0.000000    1.000000
AgeGroup 40_60    0.000000   0.000000    0.000000    0.000000
AgeGroup >60      0.000000   0.000000    0.000000    0.000000

ii) Correlation (Grip strength vs Frailty)


*  Calculates Pearson correlation between grip strength and frailty.
*  A negative correlation (like -0.71) means:
    *  Higher grip strength → Lower frailty risk.

In [17]:
correlation = df["Grip_strength"].corr(df["Frailty_binary"])
print("\nCorrelation (Grip_strength vs Frailty_binary):", correlation)

Correlation (Grip_strength vs Frailty_binary): -0.4758668672668007

In [18]:
with open("../results/findings.md", "w") as f:
    f.write("# EDA & Findings\n")
    f.write("## 1. Summary Table\n")
    f.write(summary_stats.to_markdown())
    f.write("\n")
    f.write("## 2. Correlation between Grip Strength and Frailty\n")
    f.write(f"Correlation between Grip_strength and Frailty_binary: {correlation:}\n")